/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description 202 rather than 201: the run is queued, and for a queued one there is
         *     nothing at its URL yet.
         */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Active */
        get: operations["read_active_api_runs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Finish the current stage, write its checkpoint, then end. The run
         *     stays resumable, which is what the button promises.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort Run
         * @description End now. Ingest is the exception: `fetch_evidence` is one opaque
         *     `asyncio.run()` with no interior checkpoint, so an abort during it takes
         *     effect when the fetch returns — which is what the UI's "aborting…" state
         *     is for.
         */
        post: operations["abort_run_api_runs__run_id__abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Log lines and progress ticks, until the run ends.
         *
         *     Polls the run's buffer rather than being pushed to. A quarter-second of
         *     latency on a log line is invisible, and polling keeps the logging handler
         *     free of any reference to the event loop — which is what lets the same
         *     handler work under `TestClient` and under the dev harness.
         *
         *     A tick carries no payload. The observer has already written
         *     `run_records`, `run_stages` and `run_topics` from the worker thread, so
         *     the client refetches rather than being handed the same data twice.
         */
        get: operations["stream_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/topics/{topic_id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Renders
         * @description 202, and the rows come back `generating`.
         *
         *     The rows are written before this returns rather than when the job
         *     finishes: the database is authoritative for whether a render exists,
         *     so a tile with no row behind it would vanish on the next reload. A
         *     `generating` row's `caption_slots` and — for an auto render — its
         *     rationale are not filled in yet and must not be read.
         *
         *     A bare list rather than an envelope, per `api/schemas.py`: there are no
         *     aggregates to carry.
         */
        post: operations["create_renders_api_runs__run_id__topics__topic_id__renders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Settings
         * @description Built from a fresh `Settings()`, not `app.state.settings`.
         *
         *     `app.state.settings` is frozen at startup (`create_app`'s parameter),
         *     and `init_settings` outranks the table in `Settings.settings_customise_
         *     sources` — so `getattr` on that frozen object would never see a value a
         *     `PUT` had since written, no matter how recently. The chip beside it
         *     would say "settings" while the value shown was the old one: the worst
         *     possible presentation, because it names the very layer that just won as
         *     the source of a value that layer did not produce. A fresh `Settings()`
         *     re-resolves every field through the normal precedence chain — including
         *     `SettingsTableSource`, which reads the table at construction — so a
         *     `PUT` is visible to the very next `GET`. `write_settings` already built
         *     one of these to answer its own response before this existed as its own
         *     read path; this makes that the only place that ever needs to.
         */
        get: operations["read_settings_api_settings_get"];
        /**
         * Write Settings
         * @description Write the seven tunables, then report every field's new state.
         *
         *     Same response shape as the `GET`, so the screen re-renders its source
         *     chips from this reply rather than issuing a second request.
         */
        put: operations["write_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run */
        get: operations["read_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ranking */
        get: operations["read_ranking_api_runs__run_id__topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Topic */
        get: operations["read_topic_api_runs__run_id__topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Log */
        get: operations["read_log_api_runs__run_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renders/{render_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Render */
        get: operations["read_render_api_renders__render_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove Render
         * @description 204 and no body. The row goes first, then both files.
         *
         *     A render whose PNG is already missing still deletes cleanly: the row is
         *     what makes it exist, and the end state is the same either way.
         *
         *     The meme count every screen shows is `COUNT(*)` over `renders` at query
         *     time, so nothing else has to be told this happened — which is the
         *     reason that count is not a column.
         */
        delete: operations["remove_render_api_renders__render_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renders/{render_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Image */
        get: operations["read_image_api_renders__render_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Index */
        get: operations["read_index_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Options */
        get: operations["read_options_api_config_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveRuns */
        ActiveRuns: {
            /** Current */
            current: string | null;
            /** Queued */
            queued: string[];
        };
        /**
         * AutoOrigin
         * @description A render the model briefed: it chose the template and said why.
         */
        AutoOrigin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provenance: "auto";
            /** Rationale */
            rationale: string;
        };
        /**
         * ConfigOptions
         * @description `anthropic_key_present` is a boolean and the key itself is never
         *     returned, in any form.
         */
        ConfigOptions: {
            /** Models */
            models: {
                [key: string]: string[];
            };
            /** Platforms */
            platforms: components["schemas"]["PlatformOption"][];
            /** Templates */
            templates: components["schemas"]["TemplateOption"][];
            /** Defaults */
            defaults: {
                [key: string]: string;
            };
            /** Anthropic Key Present */
            anthropic_key_present: boolean;
        };
        /**
         * Dossier
         * @description A model-generated, distilled summary of a trend
         */
        Dossier: {
            /** What Happened */
            what_happened: string;
            /** Key Entities */
            key_entities?: string[];
            /** Conversation Summary */
            conversation_summary: string;
            conversation_register: components["schemas"]["Register"];
            /** Secondary Registers */
            secondary_registers?: components["schemas"]["Register"][];
            event_sentiment: components["schemas"]["Sentiment"];
            /** Meme Potential */
            meme_potential?: number | null;
            /** Recurring Phrases */
            recurring_phrases?: components["schemas"]["Phrase"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndexedTopic
         * @description One card in the topics index.
         *
         *     `run_count` is how many runs in the window carried this topic, keyed on
         *     its label slug — `SEEN IN 3 RUNS` on the card, or `NEW THIS RUN` at one.
         */
        IndexedTopic: {
            topic: components["schemas"]["TopicRow"];
            /** Run Count */
            run_count: number;
            /** Render Count */
            render_count: number;
        };
        /**
         * LLMGeneration
         * @description Ask the model to write `count` briefs against one named template.
         *
         *     The template is named rather than chosen, because the panel already
         *     made that choice. The model writes captions for it and explains them.
         */
        LLMGeneration: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "llm";
            /** Template Id */
            template_id: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /**
         * LogLine
         * @description One line of a run's log.
         *
         *     `seq` orders lines within a run: two lines can share a timestamp at the
         *     resolution the handler records, and the live log's ordering has to be
         *     total.
         */
        LogLine: {
            /** Seq */
            seq: number;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Level */
            level: string;
            /** Logger */
            logger: string;
            /** Message */
            message: string;
        };
        /**
         * ManualGeneration
         * @description Render captions a person typed.
         *
         *     No `count`: the captions describe exactly one meme, and a count beside
         *     them would be a representable state with no meaning. No model call, so
         *     nothing to explain either — the row's `ManualOrigin` has no rationale
         *     field at all.
         */
        ManualGeneration: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "manual";
            /** Template Id */
            template_id: string;
            /** Caption Slots */
            caption_slots: {
                [key: string]: string;
            };
        };
        /**
         * ManualOrigin
         * @description A render written by hand. No model call, so no choice to explain.
         */
        ManualOrigin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provenance: "manual";
        };
        /**
         * Phrase
         * @description A repeated phrase detected in items relating to a trending topic.
         *
         *     A phrase is stored alongside the number of times it was used and the number of
         *     distinct authors that used it. This is calculated deterministically, rather than
         *     being model-generated, to avoid unnecessary hallucinations.
         *
         *     The more times a phrase is used in a topic, the more likely it is to be a specific
         *     part of the zeitgeist, and therefore the more likely it is to be either part of a
         *     caption, or a meme in its own right.
         */
        Phrase: {
            /** Text */
            text: string;
            /** Occurrences */
            occurrences: number;
            /** Distinct Authors */
            distinct_authors: number;
        };
        /**
         * PlatformOption
         * @description `enabled` is False for the dormant platforms — Lemmy and Wikipedia
         *     have code and tests but no live stage consumes a flat item list, and
         *     `Settings` rejects them. Reported rather than hidden so the screen can
         *     say why they are unavailable.
         */
        PlatformOption: {
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
        };
        /**
         * QueuedRun
         * @description `position` 0 means executing now; higher means waiting behind that
         *     many runs, which is what the "queues it behind" notice reads.
         */
        QueuedRun: {
            /** Run Id */
            run_id: string;
            /** Position */
            position: number;
        };
        /**
         * RankedTopic
         * @description One row of the ranking list.
         *
         *     `above_cut` is computed from the run's frozen `top_count` rather than
         *     left to the client: the screen draws rows below the cut dashed and
         *     dimmed with a generate link, so the rule is load-bearing.
         */
        RankedTopic: {
            topic: components["schemas"]["TopicRow"];
            /** Render Count */
            render_count: number;
            /** Above Cut */
            above_cut: boolean;
        };
        /**
         * Register
         * @description The posture people are taking towards an event.
         *
         *     This is distinct from how the event itself feels. A grim event can be treated with
         *     gallows humor or with sincere mourning, and the register captures that difference.
         * @enum {string}
         */
        Register: "tribute" | "mourning" | "delight" | "outrage" | "dunking" | "gallows" | "riffing" | "awe" | "alarm" | "debate" | "resignation";
        /**
         * RenderRecord
         * @description One rendered meme. The database is authoritative for whether it exists;
         *     the PNG and its thumbnail live at `output/<run_id>/renders/<id>.png`.
         *
         *     While `status` is `"generating"`, `caption_slots` and `origin`'s
         *     `rationale` (on `AutoOrigin`) are not yet written — they hold
         *     placeholder values until the job finishes drawing this render — and
         *     must not be read as its real captions or the model's real reasoning.
         */
        RenderRecord: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Topic Id */
            topic_id: string;
            /** Template Id */
            template_id: string;
            /** Caption Slots */
            caption_slots: {
                [key: string]: string;
            };
            /** Origin */
            origin: components["schemas"]["AutoOrigin"] | components["schemas"]["ManualOrigin"];
            /**
             * Status
             * @enum {string}
             */
            status: "generating" | "ready" | "failed";
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReplyOut
         * @description One reply, as the dossier shows it.
         *
         *     No author, handle or avatar. `Reply.author_key` exists only to count the
         *     distinct accounts behind a repeated phrase; the project stores no
         *     personal data and an API that returned it would undo that.
         */
        ReplyOut: {
            /** Text */
            text: string;
            /** Like Count */
            like_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ResumeBody
         * @description `stage` omitted means the computed resume point — the button posts no
         *     stage. `template_ids` narrows the library for this resume only, which is
         *     the tuning loop: edit a manifest, re-render the same frozen topics.
         */
        ResumeBody: {
            stage?: components["schemas"]["Stage"] | null;
            /** Template Ids */
            template_ids?: string[] | null;
        };
        /**
         * RunActionAck
         * @description Acknowledges `POST /{run_id}/stop` and `/abort`.
         *
         *     Both endpoints returned a bare `dict[str, str]`, unlike every other
         *     endpoint in the project, which declares a `response_model`. Phase 5
         *     generates a TypeScript client from this OpenAPI schema, and two
         *     undeclared response bodies out of fifteen endpoints is a client-visible
         *     hole this closes.
         */
        RunActionAck: {
            /** Run Id */
            run_id: string;
            /**
             * Requested
             * @enum {string}
             */
            requested: "stop" | "abort";
        };
        /**
         * RunConfig
         * @description The settings a run used, frozen at its start.
         *
         *     A copy rather than a reference: run detail's config line and the "Re-run
         *     config" action must show what the run actually used, which is not
         *     recoverable from a `.env` that has since been edited.
         */
        RunConfig: {
            /** Sources */
            sources: string[];
            /** Trend Limit */
            trend_limit: number;
            /** Posts Per Trend */
            posts_per_trend: number;
            /** Top Count */
            top_count: number;
            /** Meme Potential Weight */
            meme_potential_weight: number;
            /** Phrase Min Authors */
            phrase_min_authors: number;
            /** Distil Char Budget */
            distil_char_budget: number;
            /** Distil Concurrency */
            distil_concurrency: number;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Template Ids */
            template_ids: string[] | null;
        };
        /**
         * RunDetail
         * @description One run's header: what it was configured with, how its stages went,
         *     and where a resume would start.
         */
        RunDetail: {
            run: components["schemas"]["RunRecordRow"];
            /** Stages */
            stages: components["schemas"]["StageRecord"][];
            resume_stage: components["schemas"]["Stage"] | null;
        };
        /**
         * RunError
         * @description Why a run failed, and where.
         *
         *     `kind` is the exception class name rather than the instance, because the
         *     Runs screen renders it as a label — "RenderError in generate".
         */
        RunError: {
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            stage: components["schemas"]["Stage"];
        };
        /**
         * RunPage
         * @description One page of runs. `next_cursor` is None on the last page.
         */
        RunPage: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * RunRecordRow
         * @description A row of `run_records`, read back.
         *
         *     The counts are `| None` because they are written when the run finishes;
         *     a run still in flight has not counted anything yet.
         */
        RunRecordRow: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ok" | "failed" | "aborted" | "interrupted";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            config: components["schemas"]["RunConfig"];
            error: components["schemas"]["RunError"] | null;
            /** Item Count */
            item_count: number | null;
            /** Trends Found */
            trends_found: number | null;
            /** Topics Kept */
            topics_kept: number | null;
            /** Phrases Found */
            phrases_found: number | null;
        };
        /**
         * RunSummary
         * @description One row of the Runs list.
         *
         *     `topic_labels` and `render_ids` are joins the row needs and the run
         *     record does not carry: column two is the titles, column four the
         *     thumbnails.
         */
        RunSummary: {
            run: components["schemas"]["RunRecordRow"];
            /** Topic Labels */
            topic_labels: string[];
            /** Render Ids */
            render_ids: string[];
        };
        /**
         * Sentiment
         * @description How a given topic of event feels, separate from specific reactions to it.
         *
         *     Fixed taxonomy so results are comparable across runs.
         * @enum {string}
         */
        Sentiment: "cute" | "heartwarming" | "funny" | "awe" | "schadenfreude" | "outrage" | "sad" | "scary" | "gross" | "cringe" | "mundane";
        /**
         * SettingField
         * @description One tunable field, its effective value, and which layer supplied it.
         */
        SettingField: {
            /** Key */
            key: string;
            /** Value */
            value: number;
            /**
             * Source
             * @enum {string}
             */
            source: "settings" | "environment" | "dotenv" | "default";
        };
        /**
         * SettingsUpdate
         * @description An empty string clears that field's row so the `.env` fallback
         *     applies again, which is what "Reset to .env" does.
         */
        SettingsUpdate: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "ingest" | "analyse" | "evaluate" | "generate";
        /**
         * StageRecord
         * @description One stage of one run.
         *
         *     Every `| None` here is a real state: a queued stage has not started, a
         *     running one has not finished, and a failed or skipped one wrote no
         *     checkpoint.
         *
         *     `done` and `total` are the stage-relative counters the in-flight card
         *     draws as `17 / 25`, and the partial fill on its top bar. They default
         *     to None because two of the four stages have nothing to count — ingest
         *     is one opaque fetch and evaluate one ranking pass — so requiring every
         *     construction site to spell out `done=None, total=None` would state
         *     nothing four times over. A running stage that reports no counters
         *     renders an indeterminate bar rather than a zero-length one.
         */
        StageRecord: {
            stage: components["schemas"]["Stage"];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "ok" | "failed" | "skipped";
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Payload Bytes */
            payload_bytes: number | null;
            /** Summary */
            summary: string;
            /** Done */
            done?: number | null;
            /** Total */
            total?: number | null;
        };
        /**
         * StartRunBody
         * @description What `POST /api/runs` accepts.
         *
         *     `overrides` is `str`-valued because the values come from a form and are
         *     validated by `Settings` when the worker freezes the run's config — the
         *     one place that knows each field's real type.
         */
        StartRunBody: {
            /** Template Ids */
            template_ids?: string[] | null;
            /**
             * Overrides
             * @default {}
             */
            overrides: {
                [key: string]: string;
            };
        };
        /** TemplateOption */
        TemplateOption: {
            /** Id */
            id: string;
            /** Slots */
            slots: string[];
        };
        /**
         * TopicDetail
         * @description One topic's dossier: the row, the prose, what people said, and what
         *     was rendered from it.
         */
        TopicDetail: {
            topic: components["schemas"]["TopicRow"];
            dossier: components["schemas"]["Dossier"] | null;
            /** Score Components */
            score_components: {
                [key: string]: number;
            };
            /** Replies */
            replies: components["schemas"]["ReplyOut"][];
            /** Renders */
            renders: components["schemas"]["RenderRecord"][];
            recurrence: components["schemas"]["TopicRecurrence"];
        };
        /**
         * TopicIndex
         * @description The topics index and the aggregates drawn beside it.
         *
         *     `status_totals` counts the whole window rather than the filtered list,
         *     because the filter chips show every bucket's total while one of them is
         *     active. `previous_sentiment_totals` is the run before the window, which
         *     is what the mood line's "versus the previous run" compares against.
         */
        TopicIndex: {
            /** Topics */
            topics: components["schemas"]["IndexedTopic"][];
            /** Status Totals */
            status_totals: {
                [key: string]: number;
            };
            /** Sentiment Totals */
            sentiment_totals: {
                [key: string]: number;
            };
            /** Previous Sentiment Totals */
            previous_sentiment_totals: {
                [key: string]: number;
            };
        };
        /**
         * TopicRecurrence
         * @description How often this topic has been seen, keyed on its label slug.
         *
         *     A floor rather than a total: the slug fixes case and punctuation drift
         *     across runs but not wording drift, so a relabelled topic reads as new.
         */
        TopicRecurrence: {
            /** Run Count */
            run_count: number;
            /** First Seen Run Id */
            first_seen_run_id: string | null;
        };
        /**
         * TopicRow
         * @description One row of `run_topics`.
         */
        TopicRow: {
            /** Run Id */
            run_id: string;
            /** Topic Id */
            topic_id: string;
            /** Label */
            label: string;
            /** Label Slug */
            label_slug: string;
            /**
             * Trend Status
             * @enum {string}
             */
            trend_status: "trending" | "saturating" | "cooling" | "stale";
            /** Event Sentiment */
            event_sentiment: string | null;
            /** Conversation Register */
            conversation_register: string | null;
            /** Meme Potential */
            meme_potential: number | null;
            /** Trend Score */
            trend_score: number;
            /** Final Score */
            final_score: number;
            /** Final Rank */
            final_rank: number;
            /** Post Count */
            post_count: number;
            /** Top Phrase */
            top_phrase: string | null;
            /** Top Phrase Authors */
            top_phrase_authors: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_active_api_runs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveRuns"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_run_api_runs__run_id__abort_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunActionAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_renders_api_runs__run_id__topics__topic_id__renders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMGeneration"] | components["schemas"]["ManualGeneration"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingField"][];
                };
            };
        };
    };
    write_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingField"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ranking_api_runs__run_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedTopic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_topic_api_runs__run_id__topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_log_api_runs__run_id__log_get: {
        parameters: {
            query?: {
                verbose?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogLine"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_render_api_renders__render_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                render_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_render_api_renders__render_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                render_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_image_api_renders__render_id__image_get: {
        parameters: {
            query?: {
                size?: "full" | "thumb";
            };
            header?: never;
            path: {
                render_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_index_api_topics_get: {
        parameters: {
            query?: {
                window?: number;
                status?: ("trending" | "saturating" | "cooling" | "stale") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicIndex"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_options_api_config_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOptions"];
                };
            };
        };
    };
}
