import logging
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import pytest
from pydantic import ValidationError

from tests.api_factory import GatedGenerate
from tests.run_factory import make_render_record, make_run_config, make_topic
from tests.template_factory import make_manifest, make_slot, write_library
from zeitgeist.config import Settings
from zeitgeist.generation import (
    MAX_RENDERS,
    GenerationJob,
    GenerationRefused,
    GenerationService,
    LLMGeneration,
    ManualGeneration,
    RunBusy,
    UnknownTopic,
    generate_renders,
)
from zeitgeist.llm.base import FakeLLMProvider, LLMError
from zeitgeist.media.brief import BriefChoice
from zeitgeist.media.templates import load_templates
from zeitgeist.records import AutoOrigin, ManualOrigin, RenderRecord
from zeitgeist.renders import render_paths
from zeitgeist.store import MissingCheckpoint, Store, UnknownRun

TEMPLATE = "shape_alpha"
SLOTS = {"rejected": "queueing forever", "preferred": "the airport cat"}


def _settings(tmp_path) -> Settings:
    """The settings every job in this module runs under.

    `anthropic_api_key` is set because `GenerationService.submit` calls
    `build_provider` on the request thread, and `llm_provider` defaults to
    `"anthropic"`, whose factory raises `ValueError` on an empty key —
    which a freshly constructed `Settings` has, since nothing populates it
    and there is no environment for a real key to leak in from. Without
    this every `LLMGeneration` test would die in `submit` before reaching
    the behaviour it names. It stays hermetic: `AnthropicProvider.__init__`
    only constructs the SDK client and makes no network call, and every
    test here supplies its own `FakeLLMProvider` for the actual work.
    """
    return Settings(
        output_dir=tmp_path / "output",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            make_manifest(
                TEMPLATE,
                slots=[
                    make_slot("rejected", box=(10, 10, 190, 90)),
                    make_slot("preferred", box=(10, 110, 190, 190)),
                ],
            ),
        ),
    )


def _store(tmp_path, *, shared: bool = False) -> Store:
    """A fresh store with `run-1` — the run every test in this file
    generates against — already opened.

    `renders.run_id` references `run_records` and foreign keys are
    enforced, so a `generating` row for a run nobody opened is refused.
    Production only ever generates against a run that exists: the endpoint
    404s an unknown one before `submit` is reached.

    `shared` opens it with `check_same_thread=False`, as `create_app` opens
    the app's. A test whose worker writes through the service's own store —
    the path taken when the worker cannot open one of its own — needs it,
    or that write is refused on the wrong thread and lost in a `Future`
    nobody reads.
    """
    store = Store(tmp_path / "z.db", check_same_thread=not shared)
    store.init_schema()
    store.start_run("run-1", make_run_config())
    return store


def _seeded(store: Store, rid: str, **overrides) -> RenderRecord:
    """A row as `GenerationService._seed` would have written it.

    The defaults are merged rather than splatted alongside `**overrides`,
    which would raise `TypeError: got multiple values for 'caption_slots'`
    the moment a test overrides one of them — and the manual tests do.
    """
    defaults: dict = dict(
        run_id="run-1",
        topic_id="airport-cat",
        template_id=TEMPLATE,
        status="generating",
        caption_slots={},
        created_at=datetime(2026, 9, 1, tzinfo=UTC),
    )
    record = make_render_record(rid, **(defaults | overrides))
    store.add_render(record)
    return record


def _job(tmp_path, request, records, provider=None) -> GenerationJob:
    settings = _settings(tmp_path)
    return GenerationJob(
        settings=settings,
        request=request,
        topic=make_topic("airport-cat"),
        templates=load_templates(settings.templates_dir),
        records=records,
        provider=provider,
    )


def test_a_hand_written_render_becomes_ready_with_the_captions_given(tmp_path):
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == ManualOrigin()


def test_a_hand_written_render_writes_both_files(tmp_path):
    """Thumbnails are generated by the same code path that writes the
    render, so the grid never scales an 800KB PNG down to 42px."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    job = _job(
        tmp_path,
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        [record],
    )

    generate_renders(job, store)

    paths = render_paths(job.settings.output_dir, "run-1", "rnd1")
    assert paths.full.is_file()
    assert paths.thumb.is_file()


def test_a_model_written_render_records_the_rationale_it_came_back_with(tmp_path):
    """The full-size view shows WHY THIS TEMPLATE, so the rationale has to
    survive from the brief onto the row."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1")
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots=SLOTS,
                rationale="the contrast fits the joke",
            )
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE), [record], provider),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == AutoOrigin(rationale="the contrast fits the joke")


def test_the_model_is_only_offered_the_template_the_panel_named(tmp_path):
    """The choice was already made in the UI, so the prompt's library is
    narrowed to one and the model writes captions rather than picking.

    This test builds its own two-template library rather than using
    `_settings`. With the module's usual one-template library, `job.
    templates` and the narrowed `{template_id: ...}` hold the same single
    entry, so deleting the narrowing in `_brief_for` would produce an
    identical prompt and this test could not fail for the behaviour it
    names.
    """
    store = _store(tmp_path)
    settings = Settings(
        output_dir=tmp_path / "output",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            *(
                make_manifest(
                    tid,
                    slots=[
                        make_slot("rejected", box=(10, 10, 190, 90)),
                        make_slot("preferred", box=(10, 110, 190, 190)),
                    ],
                )
                for tid in (TEMPLATE, "shape_other")
            ),
        ),
    )
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r")
        ]
    )

    generate_renders(
        GenerationJob(
            settings=settings,
            request=LLMGeneration(template_id=TEMPLATE),
            topic=make_topic("airport-cat"),
            templates=load_templates(settings.templates_dir),
            records=[_seeded(store, "rnd1")],
            provider=provider,
        ),
        store,
    )

    prompt = provider.calls[0].prompt
    assert f"id={TEMPLATE}" in prompt
    assert "id=shape_other" not in prompt
    assert prompt.count("id=") == 1


OTHER = "shape_other"


def _settings_with(tmp_path, *template_ids: str) -> Settings:
    """`_settings`, but with a library of several templates.

    Letting the model choose is only observable against more than one
    template: with a library of one, "the whole library" and "the template
    named" are the same prompt, and a test could not tell them apart.
    """
    return Settings(
        output_dir=tmp_path / "output",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            *(
                make_manifest(
                    tid,
                    slots=[
                        make_slot("rejected", box=(10, 10, 190, 90)),
                        make_slot("preferred", box=(10, 110, 190, 190)),
                    ],
                )
                for tid in template_ids
            ),
        ),
    )


def _choosing_job(tmp_path, records, provider) -> GenerationJob:
    """A job whose request left the template to the model."""
    settings = _settings_with(tmp_path, TEMPLATE, OTHER)
    return GenerationJob(
        settings=settings,
        request=LLMGeneration(),
        topic=make_topic("airport-cat"),
        templates=load_templates(settings.templates_dir),
        records=records,
        provider=provider,
    )


def test_letting_the_model_choose_offers_it_the_whole_library(tmp_path):
    """The panel's default. A job that narrowed to one template here would
    make "Let the LLM choose" a synonym for whichever template the code
    happened to reach first."""
    store = _store(tmp_path)
    provider = FakeLLMProvider(
        responses=[BriefChoice(template_id=OTHER, caption_slots=SLOTS, rationale="r")]
    )

    generate_renders(
        _choosing_job(tmp_path, [_seeded(store, "rnd1", template_id=None)], provider),
        store,
    )

    prompt = provider.calls[0].prompt
    assert f"id={TEMPLATE}" in prompt
    assert f"id={OTHER}" in prompt


def test_a_render_the_model_chose_for_records_the_template_it_chose(tmp_path):
    """The seeded row names no template; the finished one names the model's
    pick, which is what the tile's footer and the full-size view show.

    The model picks `OTHER`, not the first template in the library, so a
    job that filled the row in from the library instead of from the brief
    would name the wrong one.
    """
    store = _store(tmp_path)
    provider = FakeLLMProvider(
        responses=[BriefChoice(template_id=OTHER, caption_slots=SLOTS, rationale="r")]
    )

    generate_renders(
        _choosing_job(tmp_path, [_seeded(store, "rnd1", template_id=None)], provider),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.template_id == OTHER


def test_each_requested_render_gets_its_own_brief(tmp_path):
    """count=2 is two model calls and two rows, not one brief drawn twice
    — the panel offers a count so you can compare captions."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots={"rejected": text, "preferred": "x"},
                rationale="r",
            )
            for text in ("first", "second")
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    finished = store.renders_for_topic("run-1", "airport-cat")
    assert len(provider.calls) == 2
    assert sorted(r.caption_slots["rejected"] for r in finished) == ["first", "second"]


def test_a_brief_that_never_validates_leaves_a_failed_row_carrying_why(tmp_path):
    """A failed tile with a message, rather than a tile that vanishes. The
    record already holds the outcome; nothing else has to."""
    store = _store(tmp_path)
    provider = FakeLLMProvider(responses=[LLMError("the model is down")])

    generate_renders(
        _job(
            tmp_path,
            LLMGeneration(template_id=TEMPLATE),
            [_seeded(store, "rnd1")],
            provider,
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None
    assert "the model is down" in finished.error


def test_one_failed_brief_does_not_stop_the_next_one(tmp_path):
    """Per-render failure, exactly as `_render_all` already does per
    brief: three of five rendered is a real outcome."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            LLMError("transient"),
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r"),
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    statuses = {r.id: r.status for r in store.renders_for_topic("run-1", "airport-cat")}
    assert statuses == {"a": "failed", "b": "ready"}


def test_a_caption_too_long_for_its_box_leaves_a_failed_row(tmp_path):
    """RenderError is per meme. The row carries the message the tile
    shows instead of the image."""
    store = _store(tmp_path)
    slots = {"rejected": "x " * 400, "preferred": "y"}
    record = _seeded(store, "rnd1", caption_slots=slots, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=slots),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None


def test_a_render_deleted_while_generating_stays_deleted(tmp_path):
    """The database is authoritative for whether a render exists. A job
    finishing must not bring back a row somebody removed."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    store.delete_render("rnd1")

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    assert store.get_render("rnd1") is None


def test_count_above_the_cap_is_refused_by_the_model():
    """The panel's grid is 4-up, and a count of 50 is a request for fifty
    model calls on one click."""
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=MAX_RENDERS + 1)


def test_count_below_one_is_refused_by_the_model():
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=0)


def test_a_manual_request_has_no_count_field():
    """Captions somebody typed describe exactly one meme. A count beside
    them would be a representable state with no meaning — `STRICT` forbids
    extras, which is what makes that unrepresentable rather than ignored."""
    with pytest.raises(ValidationError):
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS, count=2)


def _service(tmp_path, store, **kwargs) -> GenerationService:
    return GenerationService(_settings(tmp_path), store, **kwargs)


def _seed_topics(store: Store, *topics) -> None:
    store.write_analyse_checkpoint("run-1", list(topics), 0.3)


def test_a_generation_job_opens_the_services_database(tmp_path):
    """`_run_job` used to find its database through `job.settings.db_path`.
    With that field gone it must reach the same file through the service's
    own store. Pinned on the path the worker's `Store` actually carries, so
    a job opening a different file fails on substance.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    opened: list[Path] = []

    def generate(job: GenerationJob, job_store: Store) -> None:
        opened.append(job_store.path)

    service = _service(tmp_path, store, generate=generate)
    service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert opened == [store.path]
    store.close()


@dataclass
class RecordingGenerate:
    """Captures the job instead of doing the work, so a test can assert
    what the request thread resolved without a model or Pillow."""

    jobs: list[GenerationJob] = field(default_factory=list)

    def __call__(self, job: GenerationJob, store: Store) -> None:
        self.jobs.append(job)


def test_submit_returns_generating_rows_that_are_already_in_the_database(tmp_path):
    """The tiles the client draws need real ids and must survive a
    refresh, so the rows exist before the response does."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert [r.status for r in records] == ["generating"]
    assert store.get_render(records[0].id) is not None


def test_submit_writes_one_row_per_requested_render(tmp_path):
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=3)
    )
    service.shutdown()

    assert len(records) == 3
    assert len({r.id for r in records}) == 3


def test_a_generating_auto_row_carries_no_captions_and_no_rationale_yet(tmp_path):
    """`generating` is the state in which the brief is not yet written.
    Consumers must not read either field until it is."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE)
    )
    service.shutdown()

    assert records[0].caption_slots == {}
    assert records[0].origin == AutoOrigin(rationale="")


def test_a_generating_manual_row_already_carries_its_captions(tmp_path):
    """Nothing has to be discovered for a hand-written render, so the row
    is complete from the start except for its status."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert records[0].caption_slots == SLOTS
    assert records[0].origin == ManualOrigin()


def test_a_request_that_names_no_template_seeds_rows_without_one(tmp_path):
    """The model has not chosen yet, so the row names no template — read
    back from the database, because the column has to accept that. A
    `NOT NULL` left on it refuses the insert with an `IntegrityError`
    before a single row exists."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit("run-1", "airport-cat", LLMGeneration(count=2))
    service.shutdown()

    stored = [store.get_render(record.id) for record in records]
    assert [row.template_id if row else "missing" for row in stored] == [None, None]


def test_submit_briefs_a_topic_that_was_never_ranked(tmp_path):
    """The below-the-cut `generate` link. The topic is in the analyse
    checkpoint, which holds every topic, not just the kept ones."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"), make_topic("below-the-cut"))
    recorder = RecordingGenerate()
    service = _service(tmp_path, store, generate=recorder)

    service.submit("run-1", "below-the-cut", LLMGeneration(template_id=TEMPLATE))
    service.shutdown()

    assert recorder.jobs[0].topic.id == "below-the-cut"


def test_submit_refuses_a_topic_the_run_never_saw(tmp_path):
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(UnknownTopic):
        service.submit("run-1", "no-such-topic", LLMGeneration(template_id=TEMPLATE))


def test_submit_refuses_a_template_that_is_not_in_the_library(tmp_path):
    """Refused before any row exists, so a typo costs nothing and leaves
    nothing behind."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(GenerationRefused):
        service.submit("run-1", "airport-cat", LLMGeneration(template_id="nope"))

    assert store.renders_for_topic("run-1", "airport-cat") == []


def test_submit_refuses_hand_written_captions_that_do_not_fit_the_template(tmp_path):
    """The same rule the model's answer is held to. Accepting these would
    turn a bad request into a failed tile."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(GenerationRefused):
        service.submit(
            "run-1",
            "airport-cat",
            ManualGeneration(template_id=TEMPLATE, caption_slots={"rejected": "only"}),
        )

    assert store.renders_for_topic("run-1", "airport-cat") == []


def test_submit_raises_missing_checkpoint_when_the_run_never_analysed(tmp_path):
    """A run that died in ingest has nothing to brief from, and the
    endpoint has to say that rather than 404 the topic."""
    store = _store(tmp_path)
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(MissingCheckpoint):
        service.submit("run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE))


def test_a_manual_job_is_built_with_no_provider(tmp_path):
    """A hand-written render makes no model call, so it must not need an
    API key to be accepted."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    recorder = RecordingGenerate()
    service = _service(tmp_path, store, generate=recorder)

    service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert recorder.jobs[0].provider is None


def test_on_demand_generation_appends_rather_than_replacing(tmp_path):
    """The opposite of a re-run of the generate stage: this is an additive
    action somebody took, and clearing would delete what they are
    comparing against."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    store.add_render(
        make_render_record("older", run_id="run-1", topic_id="airport-cat")
    )
    service = _service(tmp_path, store, generate=RecordingGenerate())

    service.submit("run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE))
    service.shutdown()

    ids = [r.id for r in store.renders_for_topic("run-1", "airport-cat")]
    assert "older" in ids
    assert len(ids) == 2


def test_a_job_that_raises_leaves_every_unfinished_row_failed(tmp_path):
    """A crash in the worker must not leave tiles spinning forever. The
    backstop reads the database rather than the in-memory records, so a
    row the job already finished is left alone."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))

    def explode(job: GenerationJob, store: Store) -> None:
        raise RuntimeError("the worker fell over")

    service = _service(tmp_path, store, generate=explode)
    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=2)
    )
    service.shutdown()

    finished = [store.get_render(r.id) for r in records]
    assert all(f is not None and f.status == "failed" for f in finished)
    assert all(f is not None and f.error is not None for f in finished)


def test_a_job_that_raises_leaves_an_already_finished_row_alone(tmp_path):
    """The backstop reads each row back rather than trusting the in-memory
    records: a render the job already finished before it fell over must
    keep its real outcome, not be overwritten to failed.

    Without this, dropping the `status != "generating"` half of the guard
    in `_fail_unfinished` would break nothing — the test above raises
    before any record is finished, so every row is still generating when
    the backstop runs.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))

    def finish_first_then_explode(job: GenerationJob, store: Store) -> None:
        first, _second = job.records
        store.update_render(first.model_copy(update={"status": "ready"}))
        raise RuntimeError("the worker fell over")

    service = _service(tmp_path, store, generate=finish_first_then_explode)
    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=2)
    )
    service.shutdown()

    first, second = (store.get_render(r.id) for r in records)
    assert first is not None and first.status == "ready"
    assert second is not None and second.status == "failed"


def test_a_submitted_job_really_renders_when_nothing_is_injected(tmp_path):
    """The one test that wires `submit` to the real `generate_renders`.

    Every other service test injects a fake, so the default in
    `GenerationService.__init__` — `generate or generate_renders` — is
    otherwise never exercised: pointing it at a no-op, or forgetting to
    put `records` on the job, would break nothing in the suite while
    leaving every tile in the browser generating forever.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store)

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    finished = store.get_render(records[0].id)
    assert finished is not None
    assert finished.status == "ready"
    assert render_paths(
        _settings(tmp_path).output_dir, "run-1", records[0].id
    ).full.is_file()


def test_submit_after_shutdown_is_refused_before_any_row_is_written(tmp_path):
    """A closed service must say no on the request thread, not accept the
    request and spawn a fresh non-daemon pool behind a `Store` the app's
    lifespan already closed. Without a closed flag, `_ensure_pool` reads
    the `None` that `shutdown()` leaves behind as 'not built yet' and
    builds a new one — this is the case that flag exists to catch, as
    distinct from the live-reference-to-a-dead-pool race the try/except
    around the handoff still guards below."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())
    service.shutdown()

    with pytest.raises(RuntimeError):
        service.submit(
            "run-1",
            "airport-cat",
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        )

    assert store.renders_for_topic("run-1", "airport-cat") == []


def test_submit_fails_seeded_rows_when_the_pool_refuses_after_shutdown(tmp_path):
    """Reproduces the `_ensure_pool` / `shutdown` race directly, rather
    than through actual concurrency: `_ensure_pool` releases `self._lock`
    before handing the pool reference back to `submit`, so a `shutdown()`
    landing in that gap can swap `self._pool` to `None` and shut down the
    very pool `submit` is about to call `.submit()` on. The executor then
    raises `RuntimeError: cannot schedule new futures after shutdown` —
    but only *after* `_seed` has already committed the `generating` rows,
    so without a handler those rows would never be finished.

    Calling `service.shutdown()` first would not reach this state:
    `shutdown()` sets `self._pool = None`, so the next `submit` just calls
    `_ensure_pool()` again, gets a fresh live pool, and succeeds — the
    race needs a *live reference* to a *dead* pool, which only exists
    during the actual window between `_ensure_pool` returning and
    `.submit()` running. Assigning `service._pool` directly is white-box,
    reaching past the public interface, but it is the only way to install
    that exact state without a mock: a real `ThreadPoolExecutor` that has
    already been shut down.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())
    dead_pool = ThreadPoolExecutor(max_workers=1, thread_name_prefix="dead")
    dead_pool.shutdown(wait=True)
    service._pool = dead_pool

    with pytest.raises(RuntimeError):
        service.submit(
            "run-1",
            "airport-cat",
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        )

    rows = store.renders_for_topic("run-1", "airport-cat")
    assert len(rows) == 1
    assert rows[0].status == "failed"
    assert rows[0].error is not None


MANUAL = ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS)


def test_a_run_cannot_be_excluded_while_a_job_for_it_is_in_flight(tmp_path):
    """The job would write PNGs under the run's directory after the delete
    removed it, recreating a directory nothing would ever reclaim."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    gate = GatedGenerate()
    service = _service(tmp_path, store, generate=gate)
    try:
        service.submit("run-1", "airport-cat", MANUAL)
        assert gate.entered.wait(timeout=5)

        with pytest.raises(RunBusy), service.excluding("run-1"):
            pass
    finally:
        gate.release.set()
        service.shutdown()
    store.close()


def test_a_job_in_flight_for_one_run_does_not_hold_another(tmp_path):
    """Busy is per run. Keyed on "any job at all", one topic generating
    anywhere would make every run undeletable."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    store.start_run("run-2", make_run_config())
    store.write_analyse_checkpoint("run-2", [make_topic("airport-cat")], 0.3)
    gate = GatedGenerate()
    service = _service(tmp_path, store, generate=gate)
    try:
        service.submit("run-2", "airport-cat", MANUAL)
        assert gate.entered.wait(timeout=5)

        with service.excluding("run-1"):
            pass
    finally:
        gate.release.set()
        service.shutdown()
    store.close()


def test_a_run_can_be_excluded_once_its_jobs_have_finished(tmp_path):
    """The count comes back down when a job ends. Without that, the first
    meme ever generated for a run would make it undeletable for the life
    of the process."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())
    service.submit("run-1", "airport-cat", MANUAL)
    service.shutdown()  # Waits for the job.

    with service.excluding("run-1"):
        pass
    store.close()


def test_a_run_is_not_left_excluded_forever_if_the_workers_store_fails_to_open(
    tmp_path, monkeypatch, caplog
):
    """`_run` claims the run in `submit` and must release it "however it
    ends" — including a failure before there is even a job to run.
    `Store(self._store.path)` can raise (a locked database mid `PRAGMA
    journal_mode = WAL`, say), and a locked database is not producible
    portably in a test, so this replaces `zeitgeist.generation.Store` with
    a callable that raises instead, standing in for that failure. `submit`
    itself never constructs a `Store` — it reuses the service's own
    `self._store` — so only the worker's construction inside `_run` is
    affected; `submit` still runs to completion and hands the job to the
    pool.

    The failure must also be logged: nothing else reads the `Future` this
    runs in, so a silent return here would make the job vanish without a
    trace.
    """
    store = _store(tmp_path, shared=True)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    def explode(path):
        raise RuntimeError("the worker's database could not be opened")

    monkeypatch.setattr("zeitgeist.generation.Store", explode)

    with caplog.at_level(logging.ERROR, logger="zeitgeist.generation"):
        service.submit("run-1", "airport-cat", MANUAL)
        service.shutdown()  # Waits for the job, however it ends.

    assert any(
        record.levelno == logging.ERROR and "airport-cat" in record.getMessage()
        for record in caplog.records
    )

    with service.excluding("run-1"):
        pass
    store.close()


def test_a_job_whose_store_fails_to_open_leaves_its_renders_failed(
    tmp_path, monkeypatch
):
    """Left `generating`, the seeded rows spin on topic detail forever —
    it polls while any render is generating — with nothing to tell them
    apart from work still in progress. They are failed through the
    service's own store, which is already open; only the worker's
    construction is replaced, for the reason the test above gives."""
    store = _store(tmp_path, shared=True)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    def explode(path):
        raise RuntimeError("the worker's database could not be opened")

    monkeypatch.setattr("zeitgeist.generation.Store", explode)

    [record] = service.submit("run-1", "airport-cat", MANUAL)
    service.shutdown()  # Waits for the job, however it ends.

    failed = store.get_render(record.id)
    assert failed is not None
    assert failed.status == "failed"
    assert failed.error == "RuntimeError: the worker's database could not be opened"
    store.close()


def test_excluding_releases_the_run_when_the_guarded_delete_fails(tmp_path):
    """The delete `excluding` guards can itself be refused — the run turned
    out to be live. That refusal must not leave the run excluded from
    generation for the life of the process. `match` keeps a `RunBusy` from
    `excluding` itself (also a `RuntimeError`) from satisfying the raise."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with (
        pytest.raises(RuntimeError, match="the guarded delete failed"),
        service.excluding("run-1"),
    ):
        raise RuntimeError("the guarded delete failed")

    records = service.submit("run-1", "airport-cat", MANUAL)

    assert [r.run_id for r in records] == ["run-1"]
    service.shutdown()
    store.close()


def test_overlapping_exclusions_of_one_run_hold_until_the_last_exits(tmp_path):
    """Two deletes of the same run at once — two tabs. The first to finish
    must not reopen the run to generation while the second is still inside
    its guard: the exclusion is counted, not a flag either one can clear."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with service.excluding("run-1"):
        with service.excluding("run-1"):
            pass

        with pytest.raises(UnknownRun):
            service.submit("run-1", "airport-cat", MANUAL)

    # Both have exited, so the run is open to generation again.
    records = service.submit("run-1", "airport-cat", MANUAL)

    assert [r.run_id for r in records] == ["run-1"]
    service.shutdown()
    store.close()


def test_a_refused_submit_does_not_leave_its_run_busy(tmp_path):
    """`submit` claims the run before it validates anything, so every path
    out of it that does not hand a job to the pool must let go again."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(UnknownTopic):
        service.submit("run-1", "no-such-topic", MANUAL)

    with service.excluding("run-1"):
        pass
    service.shutdown()
    store.close()


def test_submit_is_refused_for_a_run_that_is_being_deleted(tmp_path):
    """Otherwise its seed lands after the row is gone and fails on the
    foreign key as a 500."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with service.excluding("run-1"), pytest.raises(UnknownRun):
        service.submit("run-1", "airport-cat", MANUAL)

    assert store.renders_for_topic("run-1", "airport-cat") == []
    service.shutdown()
    store.close()


def test_excluding_one_run_leaves_another_free(tmp_path):
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    store.start_run("run-2", make_run_config())
    store.write_analyse_checkpoint("run-2", [make_topic("airport-cat")], 0.3)
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with service.excluding("run-1"):
        records = service.submit("run-2", "airport-cat", MANUAL)

    assert [r.run_id for r in records] == ["run-2"]
    service.shutdown()
    store.close()


def test_submit_names_a_run_that_no_longer_exists(tmp_path):
    """A delete that finished between the endpoint's own existence check
    and this call. Without the check, `read_checkpoint` answers first with
    `MissingCheckpoint` — a 409 claiming the run never analysed."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    store.delete_run("run-1")
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(UnknownRun):
        service.submit("run-1", "airport-cat", MANUAL)
    service.shutdown()
    store.close()
