from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from tests.run_factory import make_render_record, make_topic
from tests.template_factory import make_manifest, make_slot, write_library
from zeitgeist.config import Settings
from zeitgeist.generation import (
    MAX_RENDERS,
    GenerationJob,
    GenerationRefused,
    GenerationService,
    LLMGeneration,
    ManualGeneration,
    UnknownTopic,
    generate_renders,
)
from zeitgeist.llm.base import FakeLLMProvider, LLMError
from zeitgeist.media.brief import BriefChoice
from zeitgeist.media.templates import load_templates
from zeitgeist.records import AutoOrigin, ManualOrigin, RenderRecord
from zeitgeist.renders import render_paths
from zeitgeist.store import MissingCheckpoint, Store

TEMPLATE = "shape_alpha"
SLOTS = {"rejected": "queueing forever", "preferred": "the airport cat"}


def _settings(tmp_path) -> Settings:
    """The settings every job in this module runs under.

    `anthropic_api_key` is set because `GenerationService.submit` calls
    `build_provider` on the request thread, and `llm_provider` defaults to
    `"anthropic"`, whose factory raises `ValueError` on an empty key —
    which `conftest`'s autouse fixture guarantees, since it strips
    `ANTHROPIC_API_KEY` from the environment for every test. Without this
    every `LLMGeneration` test would die in `submit` before reaching the
    behaviour it names. It stays hermetic: `AnthropicProvider.__init__`
    only constructs the SDK client and makes no network call, and every
    test here supplies its own `FakeLLMProvider` for the actual work.
    """
    return Settings(
        _env_file=None,
        output_dir=tmp_path / "output",
        db_path=tmp_path / "z.db",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            make_manifest(
                TEMPLATE,
                slots=[
                    make_slot("rejected", box=(10, 10, 190, 90)),
                    make_slot("preferred", box=(10, 110, 190, 190)),
                ],
            ),
        ),
    )


def _store(tmp_path) -> Store:
    store = Store(tmp_path / "z.db")
    store.init_schema()
    return store


def _seeded(store: Store, rid: str, **overrides) -> RenderRecord:
    """A row as `GenerationService._seed` would have written it.

    The defaults are merged rather than splatted alongside `**overrides`,
    which would raise `TypeError: got multiple values for 'caption_slots'`
    the moment a test overrides one of them — and the manual tests do.
    """
    defaults: dict = dict(
        run_id="run-1",
        topic_id="airport-cat",
        template_id=TEMPLATE,
        status="generating",
        caption_slots={},
        created_at=datetime(2026, 9, 1, tzinfo=UTC),
    )
    record = make_render_record(rid, **(defaults | overrides))
    store.add_render(record)
    return record


def _job(tmp_path, request, records, provider=None) -> GenerationJob:
    settings = _settings(tmp_path)
    return GenerationJob(
        settings=settings,
        request=request,
        topic=make_topic("airport-cat"),
        templates=load_templates(settings.templates_dir),
        records=records,
        provider=provider,
    )


def test_a_hand_written_render_becomes_ready_with_the_captions_given(tmp_path):
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == ManualOrigin()


def test_a_hand_written_render_writes_both_files(tmp_path):
    """Thumbnails are generated by the same code path that writes the
    render, so the grid never scales an 800KB PNG down to 42px."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    job = _job(
        tmp_path,
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        [record],
    )

    generate_renders(job, store)

    paths = render_paths(job.settings.output_dir, "run-1", "rnd1")
    assert paths.full.is_file()
    assert paths.thumb.is_file()


def test_a_model_written_render_records_the_rationale_it_came_back_with(tmp_path):
    """The full-size view shows WHY THIS TEMPLATE, so the rationale has to
    survive from the brief onto the row."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1")
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots=SLOTS,
                rationale="the contrast fits the joke",
            )
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE), [record], provider),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == AutoOrigin(rationale="the contrast fits the joke")


def test_the_model_is_only_offered_the_template_the_panel_named(tmp_path):
    """The choice was already made in the UI, so the prompt's library is
    narrowed to one and the model writes captions rather than picking.

    This test builds its own two-template library rather than using
    `_settings`. With the module's usual one-template library, `job.
    templates` and the narrowed `{template_id: ...}` hold the same single
    entry, so deleting the narrowing in `_brief_for` would produce an
    identical prompt and this test could not fail for the behaviour it
    names.
    """
    store = _store(tmp_path)
    settings = Settings(
        _env_file=None,
        output_dir=tmp_path / "output",
        db_path=tmp_path / "z.db",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            *(
                make_manifest(
                    tid,
                    slots=[
                        make_slot("rejected", box=(10, 10, 190, 90)),
                        make_slot("preferred", box=(10, 110, 190, 190)),
                    ],
                )
                for tid in (TEMPLATE, "shape_other")
            ),
        ),
    )
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r")
        ]
    )

    generate_renders(
        GenerationJob(
            settings=settings,
            request=LLMGeneration(template_id=TEMPLATE),
            topic=make_topic("airport-cat"),
            templates=load_templates(settings.templates_dir),
            records=[_seeded(store, "rnd1")],
            provider=provider,
        ),
        store,
    )

    prompt = provider.calls[0].prompt
    assert f"id={TEMPLATE}" in prompt
    assert "id=shape_other" not in prompt
    assert prompt.count("id=") == 1


def test_each_requested_render_gets_its_own_brief(tmp_path):
    """count=2 is two model calls and two rows, not one brief drawn twice
    — the panel offers a count so you can compare captions."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots={"rejected": text, "preferred": "x"},
                rationale="r",
            )
            for text in ("first", "second")
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    finished = store.renders_for_topic("run-1", "airport-cat")
    assert len(provider.calls) == 2
    assert sorted(r.caption_slots["rejected"] for r in finished) == ["first", "second"]


def test_a_brief_that_never_validates_leaves_a_failed_row_carrying_why(tmp_path):
    """A failed tile with a message, rather than a tile that vanishes. The
    record already holds the outcome; nothing else has to."""
    store = _store(tmp_path)
    provider = FakeLLMProvider(responses=[LLMError("the model is down")])

    generate_renders(
        _job(
            tmp_path,
            LLMGeneration(template_id=TEMPLATE),
            [_seeded(store, "rnd1")],
            provider,
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None
    assert "the model is down" in finished.error


def test_one_failed_brief_does_not_stop_the_next_one(tmp_path):
    """Per-render failure, exactly as `_render_all` already does per
    brief: three of five rendered is a real outcome."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            LLMError("transient"),
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r"),
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    statuses = {r.id: r.status for r in store.renders_for_topic("run-1", "airport-cat")}
    assert statuses == {"a": "failed", "b": "ready"}


def test_a_caption_too_long_for_its_box_leaves_a_failed_row(tmp_path):
    """RenderError is per meme. The row carries the message the tile
    shows instead of the image."""
    store = _store(tmp_path)
    slots = {"rejected": "x " * 400, "preferred": "y"}
    record = _seeded(store, "rnd1", caption_slots=slots, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=slots),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None


def test_a_render_deleted_while_generating_stays_deleted(tmp_path):
    """The database is authoritative for whether a render exists. A job
    finishing must not bring back a row somebody removed."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    store.delete_render("rnd1")

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    assert store.get_render("rnd1") is None


def test_count_above_the_cap_is_refused_by_the_model():
    """The panel's grid is 4-up, and a count of 50 is a request for fifty
    model calls on one click."""
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=MAX_RENDERS + 1)


def test_count_below_one_is_refused_by_the_model():
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=0)


def test_a_manual_request_has_no_count_field():
    """Captions somebody typed describe exactly one meme. A count beside
    them would be a representable state with no meaning — `STRICT` forbids
    extras, which is what makes that unrepresentable rather than ignored."""
    with pytest.raises(ValidationError):
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS, count=2)


def _service(tmp_path, store, **kwargs) -> GenerationService:
    return GenerationService(_settings(tmp_path), store, **kwargs)


def _seed_topics(store: Store, *topics) -> None:
    store.write_analyse_checkpoint("run-1", list(topics), 0.3)


@dataclass
class RecordingGenerate:
    """Captures the job instead of doing the work, so a test can assert
    what the request thread resolved without a model or Pillow."""

    jobs: list[GenerationJob] = field(default_factory=list)

    def __call__(self, job: GenerationJob, store: Store) -> None:
        self.jobs.append(job)


def test_submit_returns_generating_rows_that_are_already_in_the_database(tmp_path):
    """The tiles the client draws need real ids and must survive a
    refresh, so the rows exist before the response does."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert [r.status for r in records] == ["generating"]
    assert store.get_render(records[0].id) is not None


def test_submit_writes_one_row_per_requested_render(tmp_path):
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=3)
    )
    service.shutdown()

    assert len(records) == 3
    assert len({r.id for r in records}) == 3


def test_a_generating_auto_row_carries_no_captions_and_no_rationale_yet(tmp_path):
    """`generating` is the state in which the brief is not yet written.
    Consumers must not read either field until it is."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE)
    )
    service.shutdown()

    assert records[0].caption_slots == {}
    assert records[0].origin == AutoOrigin(rationale="")


def test_a_generating_manual_row_already_carries_its_captions(tmp_path):
    """Nothing has to be discovered for a hand-written render, so the row
    is complete from the start except for its status."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert records[0].caption_slots == SLOTS
    assert records[0].origin == ManualOrigin()


def test_submit_briefs_a_topic_that_was_never_ranked(tmp_path):
    """The below-the-cut `generate` link. The topic is in the analyse
    checkpoint, which holds every topic, not just the kept ones."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"), make_topic("below-the-cut"))
    recorder = RecordingGenerate()
    service = _service(tmp_path, store, generate=recorder)

    service.submit("run-1", "below-the-cut", LLMGeneration(template_id=TEMPLATE))
    service.shutdown()

    assert recorder.jobs[0].topic.id == "below-the-cut"


def test_submit_refuses_a_topic_the_run_never_saw(tmp_path):
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(UnknownTopic):
        service.submit("run-1", "no-such-topic", LLMGeneration(template_id=TEMPLATE))


def test_submit_refuses_a_template_that_is_not_in_the_library(tmp_path):
    """Refused before any row exists, so a typo costs nothing and leaves
    nothing behind."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(GenerationRefused):
        service.submit("run-1", "airport-cat", LLMGeneration(template_id="nope"))

    assert store.renders_for_topic("run-1", "airport-cat") == []


def test_submit_refuses_hand_written_captions_that_do_not_fit_the_template(tmp_path):
    """The same rule the model's answer is held to. Accepting these would
    turn a bad request into a failed tile."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(GenerationRefused):
        service.submit(
            "run-1",
            "airport-cat",
            ManualGeneration(template_id=TEMPLATE, caption_slots={"rejected": "only"}),
        )

    assert store.renders_for_topic("run-1", "airport-cat") == []


def test_submit_raises_missing_checkpoint_when_the_run_never_analysed(tmp_path):
    """A run that died in ingest has nothing to brief from, and the
    endpoint has to say that rather than 404 the topic."""
    store = _store(tmp_path)
    service = _service(tmp_path, store, generate=RecordingGenerate())

    with pytest.raises(MissingCheckpoint):
        service.submit("run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE))


def test_a_manual_job_is_built_with_no_provider(tmp_path):
    """A hand-written render makes no model call, so it must not need an
    API key to be accepted."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    recorder = RecordingGenerate()
    service = _service(tmp_path, store, generate=recorder)

    service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    assert recorder.jobs[0].provider is None


def test_on_demand_generation_appends_rather_than_replacing(tmp_path):
    """The opposite of a re-run of the generate stage: this is an additive
    action somebody took, and clearing would delete what they are
    comparing against."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    store.add_render(
        make_render_record("older", run_id="run-1", topic_id="airport-cat")
    )
    service = _service(tmp_path, store, generate=RecordingGenerate())

    service.submit("run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE))
    service.shutdown()

    ids = [r.id for r in store.renders_for_topic("run-1", "airport-cat")]
    assert "older" in ids
    assert len(ids) == 2


def test_a_job_that_raises_leaves_every_unfinished_row_failed(tmp_path):
    """A crash in the worker must not leave tiles spinning forever. The
    backstop reads the database rather than the in-memory records, so a
    row the job already finished is left alone."""
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))

    def explode(job: GenerationJob, store: Store) -> None:
        raise RuntimeError("the worker fell over")

    service = _service(tmp_path, store, generate=explode)
    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=2)
    )
    service.shutdown()

    finished = [store.get_render(r.id) for r in records]
    assert all(f is not None and f.status == "failed" for f in finished)
    assert all(f is not None and f.error is not None for f in finished)


def test_a_job_that_raises_leaves_an_already_finished_row_alone(tmp_path):
    """The backstop reads each row back rather than trusting the in-memory
    records: a render the job already finished before it fell over must
    keep its real outcome, not be overwritten to failed.

    Without this, dropping the `status != "generating"` half of the guard
    in `_fail_unfinished` would break nothing — the test above raises
    before any record is finished, so every row is still generating when
    the backstop runs.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))

    def finish_first_then_explode(job: GenerationJob, store: Store) -> None:
        first, _second = job.records
        store.update_render(first.model_copy(update={"status": "ready"}))
        raise RuntimeError("the worker fell over")

    service = _service(tmp_path, store, generate=finish_first_then_explode)
    records = service.submit(
        "run-1", "airport-cat", LLMGeneration(template_id=TEMPLATE, count=2)
    )
    service.shutdown()

    first, second = (store.get_render(r.id) for r in records)
    assert first is not None and first.status == "ready"
    assert second is not None and second.status == "failed"


def test_a_submitted_job_really_renders_when_nothing_is_injected(tmp_path):
    """The one test that wires `submit` to the real `generate_renders`.

    Every other service test injects a fake, so the default in
    `GenerationService.__init__` — `generate or generate_renders` — is
    otherwise never exercised: pointing it at a no-op, or forgetting to
    put `records` on the job, would break nothing in the suite while
    leaving every tile in the browser generating forever.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store)

    records = service.submit(
        "run-1",
        "airport-cat",
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
    )
    service.shutdown()

    finished = store.get_render(records[0].id)
    assert finished is not None
    assert finished.status == "ready"
    assert render_paths(
        _settings(tmp_path).output_dir, "run-1", records[0].id
    ).full.is_file()


def test_submit_fails_seeded_rows_when_the_pool_refuses_after_shutdown(tmp_path):
    """Reproduces the `_ensure_pool` / `shutdown` race directly, rather
    than through actual concurrency: `_ensure_pool` releases `self._lock`
    before handing the pool reference back to `submit`, so a `shutdown()`
    landing in that gap can swap `self._pool` to `None` and shut down the
    very pool `submit` is about to call `.submit()` on. The executor then
    raises `RuntimeError: cannot schedule new futures after shutdown` —
    but only *after* `_seed` has already committed the `generating` rows,
    so without a handler those rows would never be finished.

    Calling `service.shutdown()` first would not reach this state:
    `shutdown()` sets `self._pool = None`, so the next `submit` just calls
    `_ensure_pool()` again, gets a fresh live pool, and succeeds — the
    race needs a *live reference* to a *dead* pool, which only exists
    during the actual window between `_ensure_pool` returning and
    `.submit()` running. Assigning `service._pool` directly is white-box,
    reaching past the public interface, but it is the only way to install
    that exact state without a mock: a real `ThreadPoolExecutor` that has
    already been shut down.
    """
    store = _store(tmp_path)
    _seed_topics(store, make_topic("airport-cat"))
    service = _service(tmp_path, store, generate=RecordingGenerate())
    dead_pool = ThreadPoolExecutor(max_workers=1, thread_name_prefix="dead")
    dead_pool.shutdown(wait=True)
    service._pool = dead_pool

    with pytest.raises(RuntimeError):
        service.submit(
            "run-1",
            "airport-cat",
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        )

    rows = store.renders_for_topic("run-1", "airport-cat")
    assert len(rows) == 1
    assert rows[0].status == "failed"
    assert rows[0].error is not None
