from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from tests.run_factory import make_render_record, make_topic
from tests.template_factory import make_manifest, make_slot, write_library
from zeitgeist.config import Settings
from zeitgeist.generation import (
    MAX_RENDERS,
    GenerationJob,
    LLMGeneration,
    ManualGeneration,
    generate_renders,
)
from zeitgeist.llm.base import FakeLLMProvider, LLMError
from zeitgeist.media.brief import BriefChoice
from zeitgeist.media.templates import load_templates
from zeitgeist.records import AutoOrigin, ManualOrigin, RenderRecord
from zeitgeist.renders import render_paths
from zeitgeist.store import Store

TEMPLATE = "shape_alpha"
SLOTS = {"rejected": "queueing forever", "preferred": "the airport cat"}


def _settings(tmp_path) -> Settings:
    """The settings every job in this module runs under.

    `anthropic_api_key` is set because `GenerationService.submit` calls
    `build_provider` on the request thread, and `llm_provider` defaults to
    `"anthropic"`, whose factory raises `ValueError` on an empty key —
    which `conftest`'s autouse fixture guarantees, since it strips
    `ANTHROPIC_API_KEY` from the environment for every test. Without this
    every `LLMGeneration` test would die in `submit` before reaching the
    behaviour it names. It stays hermetic: `AnthropicProvider.__init__`
    only constructs the SDK client and makes no network call, and every
    test here supplies its own `FakeLLMProvider` for the actual work.
    """
    return Settings(
        _env_file=None,
        output_dir=tmp_path / "output",
        db_path=tmp_path / "z.db",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            make_manifest(
                TEMPLATE,
                slots=[
                    make_slot("rejected", box=(10, 10, 190, 90)),
                    make_slot("preferred", box=(10, 110, 190, 190)),
                ],
            ),
        ),
    )


def _store(tmp_path) -> Store:
    store = Store(tmp_path / "z.db")
    store.init_schema()
    return store


def _seeded(store: Store, rid: str, **overrides) -> RenderRecord:
    """A row as `GenerationService._seed` would have written it.

    The defaults are merged rather than splatted alongside `**overrides`,
    which would raise `TypeError: got multiple values for 'caption_slots'`
    the moment a test overrides one of them — and the manual tests do.
    """
    defaults: dict = dict(
        run_id="run-1",
        topic_id="airport-cat",
        template_id=TEMPLATE,
        status="generating",
        caption_slots={},
        created_at=datetime(2026, 9, 1, tzinfo=UTC),
    )
    record = make_render_record(rid, **(defaults | overrides))
    store.add_render(record)
    return record


def _job(tmp_path, request, records, provider=None) -> GenerationJob:
    settings = _settings(tmp_path)
    return GenerationJob(
        settings=settings,
        request=request,
        topic=make_topic("airport-cat"),
        templates=load_templates(settings.templates_dir),
        records=records,
        provider=provider,
    )


def test_a_hand_written_render_becomes_ready_with_the_captions_given(tmp_path):
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == ManualOrigin()


def test_a_hand_written_render_writes_both_files(tmp_path):
    """Thumbnails are generated by the same code path that writes the
    render, so the grid never scales an 800KB PNG down to 42px."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    job = _job(
        tmp_path,
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
        [record],
    )

    generate_renders(job, store)

    paths = render_paths(job.settings.output_dir, "run-1", "rnd1")
    assert paths.full.is_file()
    assert paths.thumb.is_file()


def test_a_model_written_render_records_the_rationale_it_came_back_with(tmp_path):
    """The full-size view shows WHY THIS TEMPLATE, so the rationale has to
    survive from the brief onto the row."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1")
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots=SLOTS,
                rationale="the contrast fits the joke",
            )
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE), [record], provider),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "ready"
    assert finished.caption_slots == SLOTS
    assert finished.origin == AutoOrigin(rationale="the contrast fits the joke")


def test_the_model_is_only_offered_the_template_the_panel_named(tmp_path):
    """The choice was already made in the UI, so the prompt's library is
    narrowed to one and the model writes captions rather than picking.

    This test builds its own two-template library rather than using
    `_settings`. With the module's usual one-template library, `job.
    templates` and the narrowed `{template_id: ...}` hold the same single
    entry, so deleting the narrowing in `_brief_for` would produce an
    identical prompt and this test could not fail for the behaviour it
    names.
    """
    store = _store(tmp_path)
    settings = Settings(
        _env_file=None,
        output_dir=tmp_path / "output",
        db_path=tmp_path / "z.db",
        anthropic_api_key="key",
        templates_dir=write_library(
            tmp_path / "templates",
            *(
                make_manifest(
                    tid,
                    slots=[
                        make_slot("rejected", box=(10, 10, 190, 90)),
                        make_slot("preferred", box=(10, 110, 190, 190)),
                    ],
                )
                for tid in (TEMPLATE, "shape_other")
            ),
        ),
    )
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r")
        ]
    )

    generate_renders(
        GenerationJob(
            settings=settings,
            request=LLMGeneration(template_id=TEMPLATE),
            topic=make_topic("airport-cat"),
            templates=load_templates(settings.templates_dir),
            records=[_seeded(store, "rnd1")],
            provider=provider,
        ),
        store,
    )

    prompt = provider.calls[0].prompt
    assert f"id={TEMPLATE}" in prompt
    assert "id=shape_other" not in prompt
    assert prompt.count("id=") == 1


def test_each_requested_render_gets_its_own_brief(tmp_path):
    """count=2 is two model calls and two rows, not one brief drawn twice
    — the panel offers a count so you can compare captions."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            BriefChoice(
                template_id=TEMPLATE,
                caption_slots={"rejected": text, "preferred": "x"},
                rationale="r",
            )
            for text in ("first", "second")
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    finished = store.renders_for_topic("run-1", "airport-cat")
    assert len(provider.calls) == 2
    assert sorted(r.caption_slots["rejected"] for r in finished) == ["first", "second"]


def test_a_brief_that_never_validates_leaves_a_failed_row_carrying_why(tmp_path):
    """A failed tile with a message, rather than a tile that vanishes. The
    record already holds the outcome; nothing else has to."""
    store = _store(tmp_path)
    provider = FakeLLMProvider(responses=[LLMError("the model is down")])

    generate_renders(
        _job(
            tmp_path,
            LLMGeneration(template_id=TEMPLATE),
            [_seeded(store, "rnd1")],
            provider,
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None
    assert "the model is down" in finished.error


def test_one_failed_brief_does_not_stop_the_next_one(tmp_path):
    """Per-render failure, exactly as `_render_all` already does per
    brief: three of five rendered is a real outcome."""
    store = _store(tmp_path)
    records = [_seeded(store, "a"), _seeded(store, "b")]
    provider = FakeLLMProvider(
        responses=[
            LLMError("transient"),
            BriefChoice(template_id=TEMPLATE, caption_slots=SLOTS, rationale="r"),
        ]
    )

    generate_renders(
        _job(tmp_path, LLMGeneration(template_id=TEMPLATE, count=2), records, provider),
        store,
    )

    statuses = {r.id: r.status for r in store.renders_for_topic("run-1", "airport-cat")}
    assert statuses == {"a": "failed", "b": "ready"}


def test_a_caption_too_long_for_its_box_leaves_a_failed_row(tmp_path):
    """RenderError is per meme. The row carries the message the tile
    shows instead of the image."""
    store = _store(tmp_path)
    slots = {"rejected": "x " * 400, "preferred": "y"}
    record = _seeded(store, "rnd1", caption_slots=slots, origin=ManualOrigin())

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=slots),
            [record],
        ),
        store,
    )

    finished = store.get_render("rnd1")
    assert finished is not None
    assert finished.status == "failed"
    assert finished.error is not None


def test_a_render_deleted_while_generating_stays_deleted(tmp_path):
    """The database is authoritative for whether a render exists. A job
    finishing must not bring back a row somebody removed."""
    store = _store(tmp_path)
    record = _seeded(store, "rnd1", caption_slots=SLOTS, origin=ManualOrigin())
    store.delete_render("rnd1")

    generate_renders(
        _job(
            tmp_path,
            ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS),
            [record],
        ),
        store,
    )

    assert store.get_render("rnd1") is None


def test_count_above_the_cap_is_refused_by_the_model():
    """The panel's grid is 4-up, and a count of 50 is a request for fifty
    model calls on one click."""
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=MAX_RENDERS + 1)


def test_count_below_one_is_refused_by_the_model():
    with pytest.raises(ValidationError):
        LLMGeneration(template_id=TEMPLATE, count=0)


def test_a_manual_request_has_no_count_field():
    """Captions somebody typed describe exactly one meme. A count beside
    them would be a representable state with no meaning — `STRICT` forbids
    extras, which is what makes that unrepresentable rather than ignored."""
    with pytest.raises(ValidationError):
        ManualGeneration(template_id=TEMPLATE, caption_slots=SLOTS, count=2)
